architect:
  - agorlov

decrypt:
  repo/coverage.sh: "repo/coverage.sh.asc"

install:
- composer install --no-ansi
#- sudo pecl install xdebug
#- echo "zend_extension=xdebug.so" > xdebug.ini    

merge:
  script: |-
    echo "MERGE"
    composer phpcs
    composer test
    composer phpstan
    bash coverage.sh
    #composer phpmd
  commanders: []
