architect:
  - agorlov

decrypt:
  repo/coverage.sh: "repo/coverage.sh.asc"

install:
- composer install --no-ansi
#- wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
#- mv test-reporter-latest-linux-amd64 ../cc-test-reporter
#- chmod +x ../cc-test-reporter
#- sudo pecl install xdebug
#- echo "zend_extension=xdebug.so" > xdebug.ini    

merge:
  script: |-
    echo "MERGE"
    composer phpcs
    composer test
    composer phpstan
    #bash coverage.sh
    #composer phpmd
  commanders: []
